[package]
name = "libtapasco_tests"
version = "0.1.0"
authors = ["Jaco Hofmann <hofmann@esa.tu-darmstadt.de>"]
edition = "2018"

[dependencies]
tapasco = { path = "../../libtapasco" }
env_logger = "0.6.0"
clap = "2.32.0"
log = "0.4.6"
snafu = "0.6.0"
