[package]
name = "tapasco"
version = "1.0.0"
authors = ["Jaco Hofmann <hofmann@esa.tu-darmstadt.de>"]
edition = "2018"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"

[dependencies]
log = "0.4.8"
chrono = "0.4.11"
libc = "0.2.69"
nix = "0.17.0"
memmap = "0.7.0"
byteorder = "1.3.4"
uom = "0.27.0"
bitflags = "1.2.1"
getset = "0.1.0"
volatile = "0.2.6"
volatile-register = "0.2.0"
page_size = "0.4.2"
generic-array = "0.14.1"
rand = "0.7.3"
snafu = "0.6.6"
prost = "0.6.1"
bytes = "0.5.4"
env_logger = "0.7.1"
lockfree = "0.5.1"
crossbeam = "0.7.3"

[build-dependencies]
prost-build = "0.6.1"
cbindgen = "0.14.2"
