[package]
name = "tapasco"
version = "0.1.0"
authors = ["Jaco Hofmann <hofmann@esa.tu-darmstadt.de>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
log = "0.4.6"
chrono = "0.4.6"
libc = "0.2.48"
nix = "0.13.0"
memmap = "0.7.0"
byteorder = "1.3.1"
uom = { version = "0.27.0" }
bitflags = "1.0.4"
getset = "0.0.6"
volatile = "0.2.6"
volatile-register = "0.2.0"
page_size = "0.4.1"
generic-array = "0.12.0"
rand = "0.6.5"
snafu = "0.6.0"
prost = "0.5.0"
bytes = "0.4.12"
env_logger = "0.7.1"

[build-dependencies]
prost-build = { version = "0.5.0" }
